---

name: Runner

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "0 0,4,8,12,16,20 * * *"  # every four hours, every day
  workflow_dispatch:

permissions: read-all

jobs:
  synchronize:
    runs-on: ubuntu-latest
    container:
      image: wesleydeanflexion/sync_github_org_team:1
      env:
        PAT: ${{ secrets.PAT }}
        TEAM_NAME: ${{ secrets.TEAM_NAME }}
        DELAY: ${{ secrets.DELAY }}
        DRY_RUN: ${{ secrets.DRY_RUN }}
        LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
        ORG: ${{ secrets.ORG }}
        USER_FILTERS: ${{ secrets.USER_FILTERS }}

    steps:
      - name: Synchronize
        run: python /workdir/sync.py
